HotelReservation/Areas/Customer/Controllers/RoomController.cs
using HotelReservation.Areas.Customer.Models;
using HotelReservation.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HotelReservation.Areas.Customer.Controllers
{
    [Area("Customer")]
	[Authorize(Roles = "Customer, Admin")]
	public class RoomController : Controller
    {
        private readonly IRoomService roomService;
        private readonly ILogger logger;

        public RoomController(IRoomService _roomService, ILogger<RoomController> _logger)
        {
            roomService = _roomService;
            logger = _logger;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var roomList = await roomService.GetAllRoomsAsync();
                return View(roomList);
            }
            catch (Exception e)
            {
                logger.LogError($"RoomController ----- Index ----- {e.Message}");
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> RoomDetails(int roomId) 
        {
            try
            {
                var room = await roomService.GetRoomByIdAsync(roomId);
                var bookModelView = new BookModelView();
                bookModelView.Room = room;
                return View(bookModelView);
            }
            catch (Exception e)
            {
                logger.LogError($"RoomController ----- RoomDetails ----- {e.Message}");
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

HotelReservation/Controllers/LoginController.cs
using HotelReservation.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HotelReservation.Controllers
{
	public class LoginController : Controller
	{
		private readonly SignInManager<AppUser> signInManager;
		private readonly UserManager<AppUser> userManager;

		public LoginController(SignInManager<AppUser> _signInManager, UserManager<AppUser> _userManager)
		{
			signInManager = _signInManager;
			userManager = _userManager;
		}

		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Index(LoginViewModel loginViewModel)
		{
			var result = await signInManager.PasswordSignInAsync(loginViewModel.UserName, loginViewModel.Password, false, true);
			if (result.Succeeded)
			{
				var user = await userManager.FindByNameAsync(loginViewModel.UserName);
				if (user.EmailConfirmed == true)
				{
					return RedirectToAction("Index", "Home");
				}
			}
			return View();
		}

		public IActionResult LogOut()
		{
			signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}
	}
}

HotelReservation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Hotel Alpha - Booking and Reservation Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/animate.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-submenu.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-select.min.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/linearicons/style.css">
    <link rel="stylesheet" type="text/css" href="~/css/jquery.mCustomScrollbar.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/dropzone.css">
    <link rel="stylesheet" type="text/css" href="~/css/slick.css">
    <link rel="stylesheet" href="css/leaflet.css" type="text/css">

    <link rel="stylesheet" type="text/css" href="~/css/initial.css">
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link rel="stylesheet" type="text/css" id="style_sheet" href="~/css/skins/default.css">

    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">

    <link href="../../../../../css2?family=Cormorant:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="../../../../../css2-1?family=Jost:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="../../../../../css2-2?family=Mulish:wght@400;500;600;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="~/css/ie10-viewport-bug-workaround.css">

    <script src="~/js/ie-emulation-modes-warning.js"></script>

</head>
<body>
    <header style="background: #F4A460;" class="top-header" id="top-header-1">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-7 col-7">
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="col-lg-4 col-md-4 col-sm-5 col-5">
                        <ul class="top-social-media pull-right">
                            <li>
                                <p class="text-white">Hi! @User.Identity.Name </p>
                            </li>
                            <li>
                                <a asp-action="LogOut" asp-controller="Login" class="sign-in"><i class="fa fa-sign-out"></i> Logout</a>
                            </li>
                            <li>
                                <a asp-action="Index" asp-controller="Account" asp-area="Customer" class="sign-in"><i class="fa-regular fa-gear"></i> Account</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="col-lg-4 col-md-4 col-sm-5 col-5">
                        <ul class="top-social-media pull-right">
                            <li>
                                <a href="/Login/Index" class="sign-in"><i class="fa fa-sign-in"></i> Login</a>
                            </li>
                            <li>
                                <a href="/Register/Index" class="sign-in"><i class="fa fa-user"></i> Register</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </div>
    </header>
    <header class="main-header" id="main-header-1">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand logos" asp-action="Index" asp-controller="Home">
                    <img src="~/img/logos/logo.png" alt="logo" class="logo-photo">
                    <img src="~/img/logos/white-logo.png" alt="logo" class="logo-photo2">
                </a>
                <button class="navbar-toggler" id="drawer" type="button">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="navbar-collapse collapse w-100 justify-content-end" id="navbar">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="@Url.Action("Index", "Room", new {Area="Customer"})" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Rooms
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Contact" asp-controller="Home">
                                Contact
                            </a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Main", new {Area="Admin"})">
                                    Admin Panel
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </nav>
            <div class="row">
                <div class="header-search animated fadeInDown">
                    <form class="form-inline">
                        <input type="text" class="form-control" id="searchKey" placeholder="Search...">
                        <div class="search-btns">
                            <button type="submit" class="btn btn-default">Search</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>



            @RenderBody()


    <!-- Footer start -->
    <footer class="main-footer clearfix">
        <div class="container">
            <!-- Footer info-->
            <div class="footer-info">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="footer-item">
                            <div class="main-title-2">
                                <h1>Contact Us</h1>
                            </div>
                            <ul class="personal-info">
                                <li>
                                    <i class="fa fa-map-marker"></i>
                                    Address: 44 New Design Street,
                                </li>
                                <li>
                                    <i class="fa fa-envelope"></i>
                                    Email:<a href="mailto:sales@hotelempire.com">info@themevessel.com</a>
                                </li>
                                <li>
                                    <i class="fa fa-phone"></i>
                                    Phone: <a href="tel:+55-417-634-7071">+0477 85X6 552</a>
                                </li>
                                <li>
                                    <i class="fa fa-fax"></i>
                                    Fax: +0477 85X6 552
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-6 col-xs-12">
                        <div class="footer-item">
                            <div class="main-title-2">
                                <h1>Booking</h1>
                            </div>
                            <ul class="links">
                                <li>
                                    <a href="rooms-col-3.html">Rooms & Suites</a>
                                </li>
                                <li>
                                    <a href="rooms-details.html">Restaurant</a>
                                </li>
                                <li>
                                    <a href="rooms-col-2.html">Hotel</a>
                                </li>
                                <li>
                                    <a href="#">Our Facilties</a>
                                </li>
                                <li>
                                    <a href="rooms-col-3.html">Rooms</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-6 col-xs-12">
                        <div class="footer-item">
                            <div class="main-title-2">
                                <h1>About</h1>
                            </div>
                            <ul class="links">
                                <li>
                                    <a href="about.html">About Us</a>
                                </li>
                                <li>
                                    <a href="blog-right-sidebar.html">Blog & Events</a>
                                </li>
                                <li>
                                    <a href="booking-system.html">Booking</a>
                                </li>
                                <li>
                                    <a href="gallery-3column.html">Gallery</a>
                                </li>
                                <li>
                                    <a href="contact.html">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="footer-item newsletter">
                            <div class="main-title-2">
                                <h1>Newsletter</h1>
                            </div>
                            <div class="newsletter-inner">
                                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                <form class="form-inline" action="#" method="GET">
                                    <input type="text" class="form-control" id="inlineFormInputName4" placeholder="Your Email">
                                    <button type="submit" class="btn btn-small"><i class="fa fa-paper-plane"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <p> &copy;  @DateTime.Now.Year <a href="http://themevessel.com/" target="_blank">FKOCA</a>. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="clearfix"></div>
                        <ul class="social-list">
                            <li><a href="#" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="rss-bg"><i class="fa fa-rss"></i></a></li>
                            <li><a href="#" class="google-bg"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#" class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer end -->


    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap-submenu.js"></script>
    <script src="~/js/jquery.mb.YTPlayer.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/bootstrap-select.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.scrollUp.js"></script>
    <script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/jquery.filterizr.js"></script>
    <script src="~/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/slick.min.js"></script>
    <script src="~/js/sidebar.js"></script>
    <script src="~/js/app.js"></script>
    <script src="~/js/dropzone.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>

    <script src="~/js/ie10-viewport-bug-workaround.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>